# Generated by Django 5.0.7 on 2024-07-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(choices=[('R1', 'Room 1'), ('R2', 'Room 2'), ('R3', 'Room 3'), ('R4', 'Room 4'), ('R5', 'Room 5')], max_length=10, unique=True)),
                ('doctor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('consultation_time', models.DateTimeField(auto_now_add=True)),
                ('recommended_treatment', models.TextField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.room')),
            ],
        ),
    ]
