# Generated by Django 5.0.7 on 2024-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(choices=[('R1', 'Room 1'), ('R2', 'Room 2'), ('R3', 'Room 3'), ('R4', 'Room 4'), ('R5', 'Room 5')], max_length=10),
        ),
    ]
